### ISSUE TITLE
No such file to load -- redmine_telegram_email/listener.rb (LoadError)

### ISSUE THREAD

**Issue by derevyov** [aekondratiev/redmine_telegram_email#8]
Hi
After run in cmd 
`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`
I'm get Error: `No such file to load -- redmine_telegram_email/listener.rb (LoadError)`

**Comment by aekondratiev** [comment]
Hello, can you run `git pull` and run bundle again

**Comment by derevyov** [comment]
Спасибо! Работает

**Comment by aekondratiev** [comment]
отлично
